language: php

sudo: false

cache:
    directories:
        - .autoconf
        - $HOME/.composer

branches:
    only:
        - master

services:
    - redis-server

php:
    - 7.0

before_script:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - bash .builds/travis.sh install
script:
    - bash .builds/travis.sh script unit
    - bash .builds/travis.sh script phpcs
